Hesai ptp params
tier4/nebula pull request #110
Opened 2023-12-27 09:15 UTC by amc-nu

## PR Type

- New Feature

## Description

Add support to the hesai hw interface to setup the Lidar's PTP profile.

## Review Procedure

You can now set up the PTP profile using the following arguments in the XML and Python launch files.

```
<arg name="ptp_profile" default="1588v2" description="1588v2|802.1as|automotive"/>
<arg name="ptp_domain" default="0" description="PTP Domain [0-127]."/>
<arg name="ptp_transport_type" default="UDP" description="1588v2 supports 'UDP' or 'L2', other profiles only L2 (HW)"/>
```

## Remarks

- Make sure you have a PTP server running on the host PC
- Only some of the sensors support all the available profiles. Please verify the respective manuals to the corresponding model you are testing with.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR**: Required to pass before the merge.

2024-02-27 11:42 UTC, drwnz commented
I tested PTP operation and the xml launchfiles. The Python launchfile does not appear to work. It does not set the rotation speed, which has a default as a non-integer causing a launch error. I will submit a PR for the rotation error issue, but the python launcher should probably access more setting (like rotation speed, destination IP).

2024-02-27 11:42 UTC, drwnz requested changes

2024-03-08 00:49 UTC, amc-nu commented on nebula_common/include/nebula_common/hesai/hesai_common.hpp
> +        std::cout << "laser " << laser_id << ", elevation " << elevation << ", azimuth " << azimuth << std::endl;
Indeed, this is a ROS-agnostic module. I removed the verbosity in: https://github.com/tier4/nebula/pull/110/commits/1d59276315b1274bf0b6cbdfe568098cbdc1dcc4

2024-03-08 00:49 UTC, amc-nu commented on nebula_hw_interfaces/src/nebula_hesai_hw_interfaces/hesai_hw_interface.cpp
> +      std::this_thread::sleep_for(100ms);
Added in https://github.com/tier4/nebula/pull/110/commits/fe8d2af31ffde899ba6e957aeb507c30372b9d80

2024-03-08 00:49 UTC, amc-nu commented on nebula_ros/launch/velodyne_launch_all_hw.xml
fixed in https://github.com/tier4/nebula/pull/110/commits/e3175a8908012ac8e75d4a13883edb85c88a3098

2024-03-08 06:27 UTC, drwnz approved these changes
LGTM, thanks!

2024-03-08 06:27 UTC, merged